# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: kimmansur.Gaugely
PackageVersion: 0.7.1
InstallerType: portable
Commands:
- gaugely
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.9
ReleaseDate: 2026-10-02
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/kimmansur/gaugely/releases/download/v0.7.1/Gaugely.exe
  InstallerSha256: 9F30B53283A299B85D04DFBB7C0E90C1B52847D05DA824A641F2BCAF45085836
ManifestType: installer
ManifestVersion: 1.12.0
